#!/bin/sh /etc/rc.common

START=99

start() {
    echo "Starting Telegram Bot"
    nohup python3 /root/androgram/androgram.py &
}

stop() {
    echo "Stopping Telegram Bot"
    killall python3
}

restart() {
    stop
    start
}
