name: Scheduled Task

on:
  schedule:
    - cron: '41 2 * * *'  # 09:40 AM Jakarta (UTC+7) corresponds to 02:40 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Add your steps here
