name: Scheduled Workflow

on:
  schedule:
    # 03:00 WIB Jakarta (UTC+7) -> 20:00 UTC (previous day)
    # 09:30 WIB Jakarta (UTC+7) -> 02:30 UTC
    - cron: '0 20 * * *'  # 03:00 WIB
    - cron: '30 2 * * *'  # 09:30 WIB
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run your task
      run: echo "Running scheduled task at $(date)"
