name: Run Workflow on File Change

on:
  push:
    paths:
      - 'run_action'  # Trigger the workflow when this file is modified

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run your action or script
        run: echo "The run_action file was modified!"
