name: Download and Save File

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #  inputs:
  #    release: 
  #      description: 将编译出的镜像上传到 Release
 #       required: true
  #      default: 'true'

jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.WORKFLOW_OVERWRITE_TOKEN }}

      - name: Download Packages Manifest
        run: |
          wget -O abc.txt https://opkg.cooluc.com/openwrt-23.05/x86_64/Packages.manifest
          grep -o 'Filename: [^ ]*' abc.txt |  awk '{print "https://opkg.cooluc.com/openwrt-23.05/x86_64/" $2}' > external-package-urls.txt
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add abc.txt
          git add external-package-urls.txt
          git commit -m "Add Packages Manifest"
          git push https://github.com/zero2black/werte_oppicial main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}