name: Download and Save File

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #  inputs:
  #    release: 
  #      description: 将编译出的镜像上传到 Release
 #       required: true
  #      default: 'true'

jobs:
  download_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download files
        run: |
          wget -P downloads https://opkg.cooluc.com/openwrt-23.05/x86_64/Packages
        # This will download the Packages file and save it to the 'downloads' directory in your repository

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloads/Packages
          git commit -m "Add downloaded Packages file"
          git push origin main
        # This will commit the downloaded Packages file to the repository and push the changes to the 'main' branch
